version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 8080:8080
    links:
      - app
      - couchdb
  couchdb:
    image: apache/couchdb:latest
    ports:
     - 5984:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
     - ~/data:/opt/couchdb/data
     - ~/etc/local.d:/opt/couchdb/etc/local.d